# Generated by Django 6.0 on 2025-12-08 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=30, verbose_name='Telefone')),
                ('servico', models.CharField(choices=[('Corte Simples', 'Corte Simples'), ('Degrade', 'Degrade'), ('Barba', 'Barba'), ('Sobrancelha', 'Sobrancelha'), ('Corte + Barba', 'Corte + Barba'), ('Pigmentacao', 'Pigmentacao')], max_length=50, verbose_name='Serviço')),
                ('data', models.DateField()),
                ('horario', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
