# Generated by Django 6.0 on 2025-12-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='servico',
        ),
        migrations.AddField(
            model_name='appointment',
            name='servicos',
            field=models.ManyToManyField(to='booking.servico'),
        ),
    ]
