# Generated by Django 6.0 on 2025-12-11 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='horario',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='nome',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='servico',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
    ]
